# -*- conf -*-
#           _ _       _
# __      _(_) |_ ___| | ____ _
# \ \ /\ / / | __/ _ \ |/ / _` |
#  \ V  V /| | ||  __/   < (_| |
#   \_/\_/ |_|\__\___|_|\_\__, |
#                         |___/
# Witek3023 | Fast & Minimal Foot Setup
# https://github.com/Witek3023

[main]
font=JetBrainsMono Nerd Font:size=11
font-size-adjustment=0.5
selection-target=both  # Select to copy

# Environment
term=xterm-256color
dpi-aware=yes
pad=15x15                     

[cursor]
style=block                           
blink=no                          

[mouse]
hide-when-typing=yes              

# NORD Colors
[colors-dark]
alpha=0.95                            
background=#2e3440                   
foreground=#eceff4                     
selection-foreground=2e3440
selection-background=#eceff4         

## Normal colors
regular0=2e3440
regular1=bf616a
regular2=a3be8c
regular3=ebcb8b
regular4=81a1c1
regular5=b48ead
regular6=88c0d0
regular7=e5e9f0

## Bright colors
bright0=4c566a
bright1=bf616a
bright2=a3be8c
bright3=ebcb8b
bright4=81a1c1
bright5=b48ead
bright6=8fbcbb
bright7=eceff4

[bell]
urgent=no
notify=no
visual=no

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=url-mode

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
[key-bindings]
pipe-scrollback=[wl-copy] Control+Shift+p   # Copy whole history
search-start=Control+Shift+r        # Search mode
show-urls-launch=Control+Shift+o    # Url mode
spawn-terminal=Control+Shift+n      # New window

[scrollback]
lines=10000            
multiplier=3.0         

[search-bindings]
cancel=Control+g Control+c Escape
commit=Return
find-prev=Control+r
find-next=Control+s

[csd]
preferred=server    # Decorations from WM