# -*- conf -*-
#           _ _       _
# __      _(_) |_ ___| | ____ _
# \ \ /\ / / | __/ _ \ |/ / _` |
#  \ V  V /| | ||  __/   < (_| |
#   \_/\_/ |_|\__\___|_|\_\__, |
#                         |___/
# Witek3023 | Fast & Minimal Foot Setup
# https://github.com/Witek3023

[main]
font=JetBrainsMono Nerd Font Mono:size=11
font-size-adjustment=0.5
selection-target=both  # Select to copy

# Environment
term=xterm-256color
dpi-aware=yes
pad=15x15                     

[cursor]
style=block                           
blink=no                          

[mouse]
hide-when-typing=yes              

[colors-dark]
alpha=1.0
background=1e1e1e
foreground=d4d4d4
selection-foreground=1e1e1e
selection-background=569cd6

regular0=1e1e1e   # black
regular1=f44747   # red
regular2=6a9955   # green
regular3=dcdcaa   # yellow
regular4=569cd6   # blue
regular5=c586c0   # magenta
regular6=4ec9b0   # cyan
regular7=d4d4d4   # white

bright0=808080
bright1=f14c4c
bright2=b5cea8
bright3=f0f0a0
bright4=9cdcfe
bright5=d7a0d7
bright6=4ec9b0
bright7=ffffff

[bell]
urgent=no
notify=no
visual=no

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
osc8-underline=url-mode

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0
[key-bindings]
pipe-scrollback=[wl-copy] Control+Shift+p   # Copy whole history
search-start=Control+Shift+r        # Search mode
show-urls-launch=Control+Shift+o    # Url mode
spawn-terminal=Control+Shift+n      # New window

[scrollback]
lines=10000            
multiplier=3.0         

[search-bindings]
cancel=Control+g Control+c Escape
commit=Return
find-prev=Control+r
find-next=Control+s

[csd]
preferred=server    # Decorations from WM