# ~/.config/fuzzel/fuzzel.ini

[main]
# Używamy tej samej czcionki co w terminalu foot
font=JetBrainsMono Nerd Font:size=14
# Terminal używany do odpalania aplikacji konsolowych
terminal=foot -e
# Znak zachęty
prompt=">  "
# Ikonki (jeśli masz zainstalowany motyw ikon Tela, Fuzzel go użyje)
icon-theme=Tela-circle-green
# Wygląd okna
lines=10
width=40
horizontal-pad=20
vertical-pad=15
inner-pad=5

[colors]
# 1e1e1e (Tło z foot) + ff (pełne krycie)
background=1e1e1eff
# d4d4d4 (Główny tekst z foot)
text=d4d4d4ff
# 6a9955 (Zielony akcent na dopasowane litery)
match=6a9955ff
# 6a9955 (Zielone tło zaznaczenia)
selection=6a9955ff
# 1e1e1e (Ciemny tekst na zielonym tle zaznaczenia)
selection-text=1e1e1eff
# 1e1e1e (Tekst dopasowany na zaznaczonym elemencie)
selection-match=1e1e1eff
# Szary kolor dla dodatkowych informacji w launcherze
border=6a9955ff

[border]
width=2
radius=8