[bar/top]
width = 100%
height = 28
clickareas = 35
background = #2E3440
foreground = #D8DEE9
foreground-alt = #000000
dpi = 110
monitor = ${env:MONITOR:}
locale = en_US.UTF-8

spacing = 4
underline-size = 2
padding-right = 5
padding-left = 2
module-margin-left = 2
module-margin-right = 2

font-0 = JetBrainsMono:style=Regular:size=9;3
font-1 = JetBrainsMono Nerd Font Mono:style=Regular:size=15;3


modules-left =label i3
modules-center = date
modules-right = volume wifi battery powermenu

[module/label]
type = custom/text
content = 

[module/battery]
type = internal/battery
full-at = 98
time-format = %H:%M

label-charging = %percentage%% 
label-discharging = %percentage%% (%time%)

format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>

[module/date]
type = internal/date
format = <label>
label = %time%
time = %H:%M
; Seconds to sleep between updates
interval = 1.0

[module/wifi]
type=internal/network
interface=wlp2s0
interval = 3.0
ping-interval = 10

format-connected = <label-connected>
label-connected = %essid%
label-disconnected = not connected
label-disconnected-foreground = #BF616A

[module/volume]
type = internal/pulseaudio

format-volume =󰓃 <label-volume>
label-muted = muted
label-muted-foreground = #BF616A


[module/i3]
type = internal/i3

pin-workspaces = true

label-focused = 
label-focused-padding = 1

label-unfocused = 
label-unfocused-padding = 1

label-visible = 
label-visible-underline = #555555
label-visible-padding = 1

label-urgent = 
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-padding = 1


[module/powermenu]
type = custom/menu

label-open = 
;label-open-background = #dd0000
;label-open-foreground = #fff
label-close = cancel
;label-close-background = #dd0000
;label-close-foreground = #fff
label-open-padding = 1 
label-close-padding = 1 

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2
menu-0-0-padding = 3
menu-0-1-padding = 3

menu-1-0 = reboot?  
menu-1-0-exec = reboot
menu-1-0-padding = 3

menu-2-0 = power off?  
menu-2-0-exec = shutdown now
menu-2-0-padding = 3

