[bar/top]
width = 100%
height = 28
clickareas = 35
background = #2E3440
foreground = #D8DEE9
foreground-alt = #000000
dpi = 110
radius = 8.0
border-size = 5
border-color = #000000000
monitor = ${env:MONITOR:}
locale = en_US.UTF-8

tray-position = center
tray-detached = false
tray-offset-x = 29%

spacing = 4
underline-size = 2
padding-right = 2
padding-left = 2
module-margin-left = 2
module-margin-right = 2

font-0 = JetBrainsMono:style=Regular:size=9;3
font-1 = JetBrainsMono Nerd Font Mono:style=Regular:size=15;3

modules-left = hostname i3
modules-center = date
modules-right = volume backlight battery powermenu

[module/hostname]
type = custom/script
format =  <label>
label = %output%
exec = hostname
interval = 1024

[module/backlight]
type = internal/backlight

card = amdgpu_bl0
enable-scroll = true

format = <ramp><label>
label = %percentage%%

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 

[module/battery]
type = internal/battery
full-at = 98
time-format = %H:%M

label-charging = %percentage%%
label-discharging = %percentage%%

format-charging = <animation-charging><label-charging>
format-discharging = <ramp-capacity><label-discharging>
format-full = <ramp-capacity><label-full>

ramp-capacity-0 = 
ramp-capacity-0-foreground = #BF616A
ramp-capacity-1 = 
ramp-capacity-1-foreground = #EBCB8B
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

[module/date]
type = internal/date
format = <label>
label = %time%
time = %H:%M
; Seconds to sleep between updates
interval = 1.0

[module/wifi]
type=internal/network
interface=wlp2s0
interval = 3.0
ping-interval = 10

format-connected =  <label-connected>
label-connected = %essid%
label-disconnected = not connected
label-disconnected-foreground = #BF616A

[module/volume]
type = internal/pulseaudio

format-volume = <ramp-volume><label-volume>
label-muted =  muted
label-muted-foreground = #BF616A

ramp-volume-0 = 
ramp-volume-1 = 

click-right = pavucontrol -t 3
[module/i3]
type = internal/i3

pin-workspaces = true

label-focused = 
label-focused-padding = 1

label-unfocused = 
label-unfocused-padding = 1

label-visible = 
label-visible-underline = #555555
label-visible-padding = 1

label-urgent = 
label-urgent-foreground = #BF616A
label-urgent-padding = 1


[module/powermenu]
type = custom/menu

label-open = 
;label-open-background = #dd0000
;label-open-foreground = #fff
label-close = cancel
;label-close-background = #dd0000
;label-close-foreground = #fff
label-open-padding = 1 
label-close-padding = 1 

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2
menu-0-0-padding = 3
menu-0-1-padding = 3

menu-1-0 = reboot?  
menu-1-0-exec = reboot
menu-1-0-padding = 3

menu-2-0 = power off?  
menu-2-0-exec = shutdown now
menu-2-0-padding = 3

